###########################################################
### 欢迎使用 Beautiful Jekyll！
### 这个配置文件用于设置影响你整个网站的选项。首次设置时，你应该遍历这些设置并进行修改，但在初始化设置后，你通常不需要频繁修改此文件。
###########################################################

############################
# --- 必填选项 --- #
############################

# 网站名称
title: 地平线

# 在页脚显示的作者名称
author: Gervas

###############################################
# --- 导航栏中的链接列表 --- #
###############################################

navbar-links:
  - [首页, /]
  - [博客, /blog]
  - [关于, "#", about]
  - [关于我, /pages/about]
  - [爱好, /pages/hobby]
  - [照片, /pages/photos]
  - [驻足, /pages/stops]
################
# --- Logo --- #
################

# 导航栏中显示的图标图片 - 最好使用方形图片
# 如果不想在导航栏中显示图片，可以删除这个参数
avatar: "/assets/img/avatar.jpg"

# 默认情况下，图像被裁切为圆形。如果你不想让头像显示为圆形，可以设置 'round-avatar: false'
round-avatar: true

# 如果你希望在左上角显示图片 Logo，而不是网站的标题，可以指定以下参数
#title-img: /path/to/image


#####################################
# --- 页脚社交媒体链接 --- #
#####################################

# 选择要在页脚显示的社交网络链接。
# 你可以通过改变此处的顺序来调整它们显示的顺序。
# 取消注释你希望显示的链接，并填写相应的信息。
social-network-links:
  email: "someone@example.com"
  github: seamoonappear
# 其他社交平台可以根据需要取消注释并添加信息
# 例如: medium、reddit、linkedin 等

# 如果你希望你的博客支持 RSS 订阅，请提供一个描述
# 订阅链接将为 https://<your_website>/feed.xml
rss-description: 这个网站是我酷炫的证明

###########################
# --- 一般设置 --- #
###########################

# 选择在文章中显示哪些社交分享按钮
share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false
  reddit: false

# 如何在页脚显示网站链接
# 如果你不想显示，可以删除此项
url-pretty: "首页"

# 在每个页面标题中添加网站标题
title-on-all-pages: false

# 摘要的字数长度 - 在 feed 页面中截断每篇文章的摘要至指定的字数
excerpt_length: 50

# 是否在 feed 页面中显示每篇博客文章的摘要
feed_show_excerpt: false

# 是否在 feed 页面中显示每篇文章的标签
feed_show_tags: true

# 在导航栏中添加搜索按钮
post_search: true

# 在页脚添加编辑当前页面的按钮。如果网站托管在 GitHub 上，则可以使用此功能
edit_page_button: true

# 允许子菜单项（第二级导航菜单项）超过顶级菜单项长度
# 如果此设置关闭，长子菜单项可能会被截断
navbar-var-length: false

# 为了SEO，指定与网站相关的关键词
#keywords: "my,list,of,keywords"

######################################
# --- 颜色 / 背景图片 --- #
######################################

# 自定义网站的颜色，颜色值可以是任何有效的 CSS 颜色

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# 或者，可以将导航栏、页脚和页面背景设置为图片，而不是颜色

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# 为移动浏览器建议一个颜色作为浏览器的主题（仅少数移动浏览器支持此功能）
#mobile-theme-col: "#0085A1"

# 如有额外的视觉定制，可以在每个页面中包含额外的 CSS 文件。列出所有自定义 CSS 文件
#site-css:
#  - "/assets/css/custom-styles.css"

# 如果有常用的 JavaScript 文件需要在每个页面中加载，可以列出这些文件
#site-js:
#  - "/assets/js/custom-script.js"

#################################
# --- 网站分析部分 --- #
#################################

# 填写你的 Google Analytics 标签 ID（或“测量 ID”）来跟踪网站使用情况
#gtag: "G-XXXXXXXXXX"

# 填写你的 Cloudflare Analytics beacon token 来通过 Cloudflare Analytics 跟踪你的网站
#cloudflare_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (前身为 Piwik) 网站统计
# 取消下面的注释启用 Matomo。opt-out 参数控制是否允许用户选择不被跟踪。
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# Google Universal Analytics ID -- 已弃用
# 从 2023 年 7 月开始，Google 不再支持该功能！如果你还在使用 `google_analytics`，
# 请切换到使用上面的 `gtag` 字段。
#google_analytics: "UA-XXXXXXXX-X"

####################
# --- 评论 --- #
####################

# 要使用 Disqus 评论，请在 https://disqus.com 注册并填写你的 Disqus shortname（不是用户 ID）
#disqus: ""

# 要使用 Facebook 评论，请创建一个 Facebook 应用并填写 Facebook App ID
#fb_comment_id: ""

# 要使用 CommentBox，请在 https://commentbox.io 注册一个项目 ID
#commentbox: ""  # 项目 ID，例如 "5694267682979840-proj"

# 要使用 Utterances 评论：（1）取消以下部分的注释，（2）填写 "repository"（确保仓库为公开仓库），
# （3）在 GitHub 仓库启用 Issues，（4）安装 Utterances 应用（https://github.com/apps/utterances）
# 更多细节请参见 https://utteranc.es/
#utterances:
#  repository: "daattali/beautiful-jekyll"  # GitHub 用户名/仓库名
#  issue-term: title   # 映射博客文章和 GitHub issues
#  theme: github-light # Utterances 主题
#  label: blog-comments # 为 Utterances 创建的 GitHub issues 分配的标签

################
# --- 其他 --- #
################

# Ruby 日期格式，用于显示文章日期
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""

#################################################################################
# --- 以下内容无需修改（除非你知道自己在做什么） --- #
#################################################################################

# 输出选项（更多信息请参考 Jekyll 官方网站）
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 10

kramdown:
  input: GFM

# 默认 YAML 值（更多信息请参考 Jekyll 官方网站）
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # 启用所有博客文章的评论
      social-share: true # 启用所有博客文章的社交媒体分享按钮
  - scope:
      path: "" # 非文章类型的页面使用 "page" 布局
    values:
      layout: "page"

# 排除这些文件不包含在生产站点中
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
